version: '3.8'
services:
  app:
    image: serendepify
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://algorizz:algorizz@postgres:5432/algorizzdb
    depends_on:
      - postgres
    networks:
      - postgres_network

  postgres:
    image: postgres:17
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=algorizz
      - POSTGRES_PASSWORD=algorizz
      - POSTGRES_DB=algorizzdb
    ports:
      - "5433:5432" # Host:5433 -> Container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U algorizz -d algorizzdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=createdliving1000@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge